---
-   name: Install Docker Compose common type
    get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        force: true
        group: docker
        mode: 'u+x,g+x'