---
#-   name: Add OpenJDK repository
#    apt_repository:
#        repo: 'deb http://ftp.us.debian.org/debian sid main'
#        state: present
#        filename: openjdk
#        update_cache: yes

-   name: Install OpenJDK 11
    apt:
        name:
            - default-jdk
        state: present
        update_cache: yes
