---
-   name: Install Docker Compose ARM version
    get_url:
        url: https://github.com/linuxserver/docker-docker-compose/releases/download/1.29.2-ls51/docker-compose-arm64
        dest: /usr/local/bin/docker-compose
        force: true
        group: docker
        mode: 'u+x,g+x'